# Generated by Django 6.0.5 on 2026-05-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('duree', models.PositiveIntegerField(help_text='Durée en heures')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
